### ISSUE TITLE
make possible to call SansSouci(.) on a set of already computed pvalues

### ISSUE THREAD

**Issue by durandg12** [sanssouci-org/sanssouci#104]
instead of data `Y`

Edit: it doesn't make sense because lambda-calibration uses permutations on the original dataset, right?

**Comment by pneuvial** [comment]
Right.

**Comment by pneuvial** [comment]
For IIDEA we are actually considering to add a vector of p values (and a vector of fold changes, aka effect sizes) to the  inputData slot of the SansSouci object, cf https://github.com/sanssouci-org/IIDEA/issues/8

@durandg12 what functionalities did you have in mind for this issue?

**Comment by durandg12** [comment]
> @durandg12 what functionalities did you have in mind for this issue?

Can't remember, I think it was just my mind wandering wrongly
