### ISSUE TITLE
Replace all example data set from GSEABenchmarkeR by local files (imported from the same source)

### ISSUE THREAD

**Issue by nicolas-enjalbert** [sanssouci-org/sanssouci#55]

**Comment by pneuvial** [comment]
Before closing this issue we should make sure that the app can be easily run locally by users. 
In particular we should pay attention to how to generate the local data sets and where the files are stored

**Comment by nicolas-enjalbert** [comment]
I add some code line to change the work directory in the file `export_GSEA_dataset.R`. This file can be executed on Rstudio for example and also with the command line `R CMD BATCH export_GSEA_dataset.R`. 
I try to find the good line to be compatible with both execution way.
