### ISSUE TITLE
Write a function that computes all zeta HB with only one p-values ordering

### ISSUE THREAD

**Issue by durandg12** [sanssouci-org/sanssouci#77]
title

**Comment by pneuvial** [comment]
Duplicate of #100

**Comment by durandg12** [comment]
Actually, it doesn't seem doable. Let sigma the ordering permutation of the p-values and tau its reciprocal permutation. If m =100 and the pvalues are naturally in decreasing order (meaning that sigma=tau=100:1), for the region 1:25 we would want to associate the number 1 to the subset 76 (because that is the lowest value of tau(1:25)=100:76), but for the region 1:50, 1 should then be associated to subset 51 (because that is the lowest value of tau(1:50)=100:51).

Said differently, even with sigma and tau known, for a given region R_k we still need to order the image tau(R_k)
